### ISSUE TITLE
3.     Lisada routerile testid:

### ISSUE THREAD

**Issue by Kadi12345** [Kadi12345/GreatSuccess-to-do-be#10]
Lisada routerile testid: iga route kohta testida seda, kas kutsub välja õige controlleri meetodi kasutades spy’sid. Lisaks testida, kas post/get meetodeid kutsutakse õige arv kordi välja. Näidiseks describe blokk (Teie teete selle järgi mitu eri route Teil on):
describe('router', () => {

  require('./../src/router');

 

  test('should use getTodoTasks controller when "/todo-tasks" is triggered', () => {

    // expect here

  });

 

  test('should use getDoneTasks controller when "/done-tasks" is triggered', () => {

    // expect here

  });

 

  test('should use moveTask controller when "/moveTask/:id/:toTask" is triggered', () => {

    // expect here

  });

 

  test('should use createTask controller when "/createTask" is triggered', () => {

    // expect here

  });

 

  test('should call post method 1 time', () => {

    // expect here

  });

 

  test('should call get method 3 times', () => {

    // expect here

  });

});

**Comment by MeelisM** [comment]
done
